gnodeb:
  controlif:
    ip: "10.141.6.5"
    port: 9487
  dataif:
    ip: "10.141.6.5"
    port: 2152
  plmnlist:
    mcc: "999"
    mnc: "70"
    tac: "000001"
    gnbid: "000008"
  slicesupportlist:
    sst: "01"
    sd: "111111" # optional, can be removed if not used

ue:
  msin: "0000000001"
  key: "465B5CE8B199B49FAA5F0A2EE238A6BC"
  opc: "E8ED289DEBA952E4283B54E88E6183CA"
  amf: "8000"
  sqn: "00000000"
  dnn: "internet"
  routingindicator: "0000"
  hplmn:
    mcc: "999"
    mnc: "70"
  snssai:
    sst: 01
    sd: "111111" # optional, can be removed if not used
amfif:
  ip: "10.140.0.139"
  port: 30009
logs:
    level: 4

#001010000001000