apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: loss
spec:
  action: loss
  mode: one
  selector:
    namespaces:
      - open5gs
    labelSelectors:
      "app.kubernetes.io/name": "amf"
  loss:
    loss: "10"
    correlation: "100"
