apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: delay
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - open5gs
    labelSelectors:
      "app.kubernetes.io/name": "ausf"
  delay:
    latency: "200ms"
    correlation: "100"
    jitter: "0ms"
