apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: jitter
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - open5gs
    labelSelectors:
      "app.kubernetes.io/name": "nrf"
  delay:
    correlation: "100"
    jitter: "500ms"
