apiVersion: v1
kind: Service
metadata:
  name: open5gs-amf-ngap-nodeport
  namespace: open5gs
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: amf
  ports:
    - name: ngap
      port: 38412
      protocol: SCTP
      targetPort: ngap
      nodePort: 30009
