apiVersion: v1
kind: Service
metadata:
  name: open5gs-webui-nodeport
  namespace: open5gs
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: webui
  ports:
    - name: http
      port: 9999
      protocol: TCP
      targetPort: http
      nodePort: 30015
